
package hai702.tp2.demo.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ExceptionAlreadyexistoffre", targetNamespace = "http://services.demo.tp2.hai702/")
public class ExceptionAlreadyexistoffre_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ExceptionAlreadyexistoffre faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ExceptionAlreadyexistoffre_Exception(String message, ExceptionAlreadyexistoffre faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ExceptionAlreadyexistoffre_Exception(String message, ExceptionAlreadyexistoffre faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: hai702.tp2.demo.client.ExceptionAlreadyexistoffre
     */
    public ExceptionAlreadyexistoffre getFaultInfo() {
        return faultInfo;
    }

}
