
package hai702.tp2.demo.client.reservation;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ReservationServiceImplService", targetNamespace = "http://services.demo.tp2.hai702/", wsdlLocation = "http://localhost:8080/effectuerReservation?wsdl")
public class ReservationServiceImplService
    extends Service
{

    private final static URL RESERVATIONSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException RESERVATIONSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName RESERVATIONSERVICEIMPLSERVICE_QNAME = new QName("http://services.demo.tp2.hai702/", "ReservationServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/effectuerReservation?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RESERVATIONSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        RESERVATIONSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public ReservationServiceImplService() {
        super(__getWsdlLocation(), RESERVATIONSERVICEIMPLSERVICE_QNAME);
    }

    public ReservationServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RESERVATIONSERVICEIMPLSERVICE_QNAME, features);
    }

    public ReservationServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, RESERVATIONSERVICEIMPLSERVICE_QNAME);
    }

    public ReservationServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RESERVATIONSERVICEIMPLSERVICE_QNAME, features);
    }

    public ReservationServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReservationServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ReservationService
     */
    @WebEndpoint(name = "ReservationServiceImplPort")
    public ReservationService getReservationServiceImplPort() {
        return super.getPort(new QName("http://services.demo.tp2.hai702/", "ReservationServiceImplPort"), ReservationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReservationService
     */
    @WebEndpoint(name = "ReservationServiceImplPort")
    public ReservationService getReservationServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.demo.tp2.hai702/", "ReservationServiceImplPort"), ReservationService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RESERVATIONSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw RESERVATIONSERVICEIMPLSERVICE_EXCEPTION;
        }
        return RESERVATIONSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
